/*
 * Independent verification harness for ITEM-003 (GXHT40 driver).
 * Author: embedded_tester.embedded_verification.
 *
 * Links the REAL USER/src/gxht40.c and USER/src/sf_i2c.c against a bit-level
 * mock I2C bus plus a mock GXHT40 device, so address probing, the 0xFD command,
 * the 6-byte frame order, the two CRC-8 checks, integer conversion, retry bounds
 * and "failure must not modify outputs" are checked without an MCU.
 *
 * The 6-byte frames used here were generated by an independent reference script
 * (CRC-8 poly 0x31 init 0xFF, MSB-first, xorout 0x00) and are hard-coded; the
 * harness never reuses the driver's own CRC/conversion code to build expectations.
 *
 * delay_ms is a counting stub (timing primitive test double), so the requested
 * tMEAS wait can be asserted.
 *
 * Build (from gpio_input_output/):
 *   gcc -std=c11 -Wall -Wextra -Wno-int-to-pointer-cast \
 *       -I USER/inc -I COMMON -I ../../../Libraries/inc -I <CMSIS 5.9.0 Core Include> \
 *       test/host_gxht40_verify_ev.c USER/src/gxht40.c USER/src/sf_i2c.c -o gxht40_verify
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "gxht40.h"
#include "sensor_config.h"
#include "delay.h"

/* ---------------- delay_ms test double ---------------- */
static uint16_t delay_log[128];
static int delay_n;
void delay_ms(uint16_t ms) { if (delay_n < 128) delay_log[delay_n++] = ms; }
static int delay_count_of(uint16_t ms) { int c = 0; for (int i = 0; i < delay_n; i++) if (delay_log[i] == ms) c++; return c; }

/* ---------------- mock bus ---------------- */
enum { EV_START = 1, EV_STOP, EV_TX, EV_TXACK, EV_RX, EV_RXMACK };
static int ev_code[4096], ev_val[4096], ev_n;
static void ev_add(int c, int v) { if (ev_n < 4096) { ev_code[ev_n] = c; ev_val[ev_n] = v; ev_n++; } }
static void ev_reset(void) { ev_n = 0; }

/* mock GXHT40 device */
static uint8_t dev_addr7 = 0x44;          /* 0 = no device */
static uint8_t frame[6] = {0x66,0x66,0x93,0x72,0xB0,0xDC};
static int     read_nack_remaining;
static int     cmd_count;
static uint8_t cmd_log[32];
static int     wr_addr_n;  static uint8_t wr_addr_log[32];
static int     rd_addr_n;  static uint8_t rd_addr_log[32];
static int     all_cmd_n;  static uint8_t all_cmd[256];   /* cumulative, never reset */

static void log_reset(void)
{
    ev_reset(); delay_n = 0; cmd_count = 0; wr_addr_n = 0; rd_addr_n = 0;
}

/* slave FSM */
enum { ST_IDLE = 0, ST_ADDR_BITS, ST_ADDR_ACK, ST_WR_BITS, ST_WR_ACK, ST_RD_BITS, ST_RD_MACK };
static int st, bitcnt, pending_ack, addr_byte, rd_idx_sh;
static uint8_t sh;

static int scl = 1, m_sda = 1, m_drive = 1, slave_sda = 1;
static int bus(void) { return m_drive ? m_sda : (slave_sda ? 1 : 0); }

static void slave_start_reset(void) { st = ST_ADDR_BITS; bitcnt = 0; addr_byte = 0; pending_ack = 0; }
static void slave_stop(void) { st = ST_IDLE; }

static void set_master_sda(int v)
{
    if (v == m_sda) return;
    if (m_drive && scl) {
        if (v == 0) { ev_add(EV_START, 0); slave_start_reset(); }
        else        { ev_add(EV_STOP, 0);  slave_stop(); }
    }
    m_sda = v;
}
static void sda_low(void)  { set_master_sda(0); }
static void sda_high(void) { set_master_sda(1); }
static void dir_in(void)   { m_drive = 0; }
static void dir_out(void)  { m_drive = 1; }
static uint8_t sda_read(void) { return (uint8_t)bus(); }

static void slave_on_fall(void)
{
    if (st == ST_ADDR_ACK || st == ST_WR_ACK) {
        slave_sda = pending_ack ? 0 : 1;
    } else if (st == ST_RD_BITS) {
        uint8_t b = (rd_idx_sh < 6) ? frame[rd_idx_sh] : 0xFF;
        slave_sda = ((b >> (7 - bitcnt)) & 1) ? 1 : 0;
    } else if (st == ST_RD_MACK) {
        slave_sda = 1;
    }
}
static void slave_on_rise(void)
{
    int lvl = bus();
    switch (st) {
    case ST_ADDR_BITS:
        addr_byte = (addr_byte << 1) | lvl; bitcnt++;
        if (bitcnt == 8) {
            uint8_t a = (uint8_t)addr_byte;
            int present = (dev_addr7 != 0u) && ((a & 0xFEu) == (uint8_t)(dev_addr7 << 1));
            if (a & 1u) {                                  /* read address */
                if (rd_addr_n < 32) rd_addr_log[rd_addr_n++] = a;
                if (present && read_nack_remaining == 0) { pending_ack = 1; }
                else { pending_ack = 0; if (present) read_nack_remaining--; }
            } else {                                       /* write address */
                if (wr_addr_n < 32) wr_addr_log[wr_addr_n++] = a;
                pending_ack = present ? 1 : 0;
            }
            st = ST_ADDR_ACK;
        }
        break;
    case ST_ADDR_ACK:
        ev_add(EV_TXACK, lvl ? 1 : 0);
        if (!pending_ack) { st = ST_IDLE; break; }
        if (addr_byte & 1) { st = ST_RD_BITS; bitcnt = 0; rd_idx_sh = 0; }
        else               { st = ST_WR_BITS; bitcnt = 0; }
        break;
    case ST_WR_BITS:
        addr_byte = (addr_byte << 1) | lvl; bitcnt++;
        if (bitcnt == 8) {
            if (cmd_count < 32) cmd_log[cmd_count++] = (uint8_t)addr_byte;
            if (all_cmd_n < 256) all_cmd[all_cmd_n++] = (uint8_t)addr_byte;
            pending_ack = 1;
            st = ST_WR_ACK;
        }
        break;
    case ST_WR_ACK:
        ev_add(EV_TXACK, lvl ? 1 : 0);
        if (!pending_ack) { st = ST_IDLE; break; }
        st = ST_WR_BITS; bitcnt = 0;
        break;
    case ST_RD_BITS:
        if (bitcnt == 0) sh = 0;
        sh = (uint8_t)((sh << 1) | lvl);
        bitcnt++;
        if (bitcnt == 8) { ev_add(EV_RX, sh); rd_idx_sh++; st = ST_RD_MACK; }
        break;
    case ST_RD_MACK:
        ev_add(EV_RXMACK, lvl ? 1 : 0);
        if (lvl == 0) { st = ST_RD_BITS; bitcnt = 0; }
        else          { st = ST_IDLE; }
        break;
    default: break;
    }
}
static void scl_low_(void)  { if (scl == 1) { scl = 0; if (st != ST_IDLE) slave_on_fall(); } }
static void scl_high_(void) { if (scl == 0) { scl = 1; if (st != ST_IDLE) slave_on_rise(); } }

static i2c_dev dev = {
    .name = "mock", .speed = 1,
    .port.sda_pin_out_low = sda_low, .port.sda_pin_out_high = sda_high,
    .port.scl_pin_out_low = scl_low_, .port.scl_pin_out_high = scl_high_,
    .port.sda_pin_read_level = sda_read,
    .port.sda_pin_dir_input = dir_in, .port.sda_pin_dir_output = dir_out,
};

static int pass, fail;
#define CHECK(c, m) do { if (c) { pass++; printf("    PASS  %s\n", m); } \
                         else   { fail++; printf("    FAIL  %s (line %d)\n", m, __LINE__); } } while (0)
static int wr_addr_seen(uint8_t v) { for (int i = 0; i < wr_addr_n; i++) if (wr_addr_log[i] == v) return 1; return 0; }
static int rd_addr_seen(uint8_t v) { for (int i = 0; i < rd_addr_n; i++) if (rd_addr_log[i] == v) return 1; return 0; }
static int all_ever_sent_are(uint8_t v) { if (all_cmd_n == 0) return 0; for (int i = 0; i < all_cmd_n; i++) if (all_cmd[i] != v) return 0; return 1; }

static void set_frame(const uint8_t f[6]) { memcpy(frame, f, 6); }

int main(void)
{
    printf("==== independent GXHT40 driver verification (embedded_tester) ====\n");
    i2c_init(&dev);
    gxht40_init(&dev);

    /* frames generated by the independent reference script (see header comment) */
    const uint8_t F_MANUAL[6]  = {0xBE,0xEF,0x92,0x12,0x34,0x37}; /* 0xBEEF/0x1234 -> 855 / 29 */
    const uint8_t F_ROOM[6]    = {0x66,0x66,0x93,0x72,0xB0,0xDC}; /* 25.0C / 50.0%RH -> 250 / 500 */
    const uint8_t F_NEG[6]     = {0x33,0x33,0x88,0x00,0x00,0x81}; /* -10.0C / 0%RH -> -100 / 0 */
    const uint8_t F_CLAMP[6]   = {0x66,0x66,0x93,0xFF,0xFF,0xAC}; /* 25.0C / raw 0xFFFF -> hum 1000 */
    const uint8_t F_HUM0[6]    = {0x66,0x66,0x93,0x00,0x00,0x81}; /* 25.0C / raw 0 -> hum 0 */
    const uint8_t F_RLOW[6]    = {0x00,0x00,0x81,0x72,0xB0,0xDC}; /* raw_t 0 -> -45.0C out of range */
    const uint8_t F_RHIGH[6]   = {0xF8,0xCA,0x32,0x72,0xB0,0xDC}; /* raw_t 0xF8CA -> 125.1C out of range */
    const uint8_t F_CRCT[6]    = {0x66,0x66,0x00,0x72,0xB0,0xDC}; /* temperature CRC bad */
    const uint8_t F_CRCH[6]    = {0x66,0x66,0x93,0x72,0xB0,0x00}; /* humidity CRC bad */

    /* ---- T1: manual reference vector + wire framing ---- */
    printf("[T1] manual reference frame 0xBEEF/0x1234\n");
    log_reset(); dev_addr7 = 0x44; read_nack_remaining = 0; set_frame(F_MANUAL); slave_start_reset();
    int16_t t = 0; uint16_t h = 0;
    gxht40_status_t r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_OK, "returns GXHT40_OK");
    CHECK(t == 855 && h == 29, "temp_x10=855, hum_x10=29 (manual vector)");
    CHECK(cmd_count == 1 && cmd_log[0] == 0xFD, "exactly one command byte 0xFD");
    CHECK(wr_addr_seen(0x88), "write address byte 0x88 used");
    CHECK(rd_addr_seen(0x89), "read address byte 0x89 used");
    CHECK(gxht40_detected_addr7() == 0x44, "detected address cached as 0x44");
    CHECK(delay_count_of(GXHT40_MEASURE_WAIT_MS) == 1, "one tMEAS wait of the configured 10 ms");

    /* ---- T2: room + negative + clamping ---- */
    printf("[T2] conversion: room / negative / humidity clamp\n");
    log_reset(); set_frame(F_ROOM); slave_start_reset();
    t = -1; h = 0xFFFF; r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_OK && t == 250 && h == 500, "25.0 C / 50.0 %RH -> 250 / 500");
    log_reset(); set_frame(F_NEG); slave_start_reset();
    t = 0; h = 0xFFFF; r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_OK && t == -100 && h == 0, "-10.0 C / 0 %RH -> -100 / 0 (sign preserved)");
    log_reset(); set_frame(F_CLAMP); slave_start_reset();
    t = 0; h = 0; r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_OK && t == 250 && h == 1000, "humidity raw 0xFFFF clamped to 1000 (not an error)");
    log_reset(); set_frame(F_HUM0); slave_start_reset();
    t = 0; h = 0xFFFF; r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_OK && h == 0, "humidity raw 0 -> 0");

    /* ---- T3: address probe 0x44/0x45 + caching ---- */
    printf("[T3] address probe: device only at 0x45, then cached\n");
    gxht40_init(&dev);                       /* clear cache */
    log_reset(); dev_addr7 = 0x45; set_frame(F_ROOM); slave_start_reset();
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_OK, "measure succeeds via second address");
    CHECK(wr_addr_n >= 2 && wr_addr_log[0] == 0x88 && wr_addr_log[1] == 0x8A, "probe order 0x88 then 0x8A");
    CHECK(rd_addr_n >= 1 && rd_addr_log[0] == 0x8B, "read address 0x8B for the 0x45 variant");
    CHECK(gxht40_detected_addr7() == 0x45, "detected address cached as 0x45");
    log_reset(); slave_start_reset();
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_OK && wr_addr_log[0] == 0x8A && !wr_addr_seen(0x88),
          "second measurement uses the cached 0x8A without re-probing 0x88");

    /* ---- T4: read NACK (conversion not ready) is retried without re-command ---- */
    printf("[T4] read NACK x2 then ready\n");
    gxht40_init(&dev); log_reset(); dev_addr7 = 0x44; set_frame(F_ROOM);
    read_nack_remaining = 2; slave_start_reset();
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_OK && t == 250 && h == 500, "succeeds after two read NACKs");
    CHECK(cmd_count == 1, "command NOT re-sent while waiting for conversion");
    CHECK(rd_addr_n == 3, "three read attempts seen (2 NACK + 1 ACK)");
    CHECK(delay_count_of(GXHT40_READ_RETRY_DELAY_MS) == 2, "two 1 ms retry waits");

    /* ---- T5: read NACK exhausted -> IO error, outputs untouched ---- */
    printf("[T5] read NACK beyond the retry bound\n");
    log_reset(); dev_addr7 = 0x44; read_nack_remaining = 99; slave_start_reset();
    t = 0x7F7F; h = 0x7F7F;
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_ERR_IO, "returns GXHT40_ERR_IO");
    CHECK(t == 0x7F7F && h == 0x7F7F, "outputs NOT modified on failure");
    CHECK(cmd_count <= (int)GXHT40_MEAS_RETRY, "command attempts bounded by GXHT40_MEAS_RETRY");
    CHECK(rd_addr_n <= (int)(GXHT40_MEAS_RETRY * GXHT40_READ_RETRY), "read attempts bounded by MEAS_RETRY*READ_RETRY");

    /* ---- T6: CRC errors -> retried then reported, outputs untouched ---- */
    printf("[T6] CRC error paths\n");
    gxht40_init(&dev); log_reset(); dev_addr7 = 0x44; read_nack_remaining = 0;
    set_frame(F_CRCT); slave_start_reset(); t = 0x1111; h = 0x2222;
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_ERR_CRC, "temperature-word CRC error -> GXHT40_ERR_CRC");
    CHECK(t == 0x1111 && h == 0x2222, "outputs NOT modified");
    CHECK(cmd_count == (int)GXHT40_MEAS_RETRY, "re-measured exactly GXHT40_MEAS_RETRY times");
    log_reset(); set_frame(F_CRCH); slave_start_reset(); t = 0x1111; h = 0x2222;
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_ERR_CRC, "humidity-word CRC error also detected");
    CHECK(t == 0x1111 && h == 0x2222, "outputs NOT modified");

    /* ---- T7: range errors ---- */
    printf("[T7] out-of-range conversion\n");
    log_reset(); set_frame(F_RLOW); slave_start_reset(); t = 0x1111; h = 0x2222;
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_ERR_RANGE, "raw 0 (-45.0 C) -> GXHT40_ERR_RANGE");
    CHECK(t == 0x1111 && h == 0x2222, "outputs NOT modified");
    log_reset(); set_frame(F_RHIGH); slave_start_reset();
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_ERR_RANGE, "125.1 C -> GXHT40_ERR_RANGE");
    CHECK(t == 0x1111 && h == 0x2222, "outputs NOT modified");

    /* ---- T8: no device ---- */
    printf("[T8] no device on either address\n");
    gxht40_init(&dev); log_reset(); dev_addr7 = 0; slave_start_reset(); t = 0x1111; h = 0x2222;
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_ERR_NO_DEVICE, "returns GXHT40_ERR_NO_DEVICE");
    CHECK(wr_addr_seen(0x88) && wr_addr_seen(0x8A), "both 0x44 and 0x45 probed");
    CHECK(t == 0x1111 && h == 0x2222, "outputs NOT modified");
    CHECK(cmd_count <= (int)(GXHT40_MEAS_RETRY * 2), "probe attempts bounded");

    /* ---- T9: parameter checks ---- */
    printf("[T9] parameter checks\n");
    log_reset(); t = 0x1111; h = 0x2222;
    r = gxht40_measure(NULL, &h);
    CHECK(r == GXHT40_ERR_PARAM && t == 0x1111 && h == 0x2222, "NULL temp pointer -> GXHT40_ERR_PARAM");
    r = gxht40_measure(&t, NULL);
    CHECK(r == GXHT40_ERR_PARAM, "NULL humidity pointer -> GXHT40_ERR_PARAM");
    gxht40_init(NULL);
    r = gxht40_measure(&t, &h);
    CHECK(r == GXHT40_ERR_PARAM, "unbound bus -> GXHT40_ERR_PARAM");
    gxht40_init(&dev);

    /* ---- T10: command whitelist across every test above ---- */
    printf("[T10] command whitelist over every command ever sent (%d total)\n", all_cmd_n);
    CHECK(all_ever_sent_are(GXHT40_CMD_MEASURE_HIGH_REP), "every command byte sent was 0xFD");
    CHECK(all_cmd_n > 0, "commands were actually exercised");

    printf("==== result: %d passed, %d failed ====\n", pass, fail);
    return fail ? 1 : 0;
}
